SELECT 
        cast(id as integer)             AS id, 
        cast(player_fifa_api_id 
             as integer)                AS player_fifa_api_id,
        cast(player_api_id as integer)  AS player_api_id, 
        cast(replace(date, ' 00:00:00', '') as date)  AS date,
        cast(overall_rating as integer) AS overall_rating,
        cast(potential as integer)      AS potential,
        upper(preferred_foot)           AS preferred_foot ,
        upper(attacking_work_rate)      AS attacking_work_rate,
        upper(defensive_work_rate)      AS defensive_work_rate,
        cast(crossing as integer)       AS crossing,
        cast(finishing as integer)      AS finishing,
        cast(heading_accuracy 
             as integer)                AS heading_accuracy,
        cast(short_passing as integer)  AS short_passing,
        cast(volleys as integer)        AS volleys, 
        cast(dribbling as integer)      AS dribbling,
        cast(curve as integer)          AS curve,
        cast(free_kick_accuracy 
            as integer)                 AS free_kick_accuracy,
        cast(long_passing as integer)   AS long_passing,
        cast(ball_control as integer)   AS ball_control, 
        cast(acceleration as integer)   AS acceleration,
        cast(sprint_speed as integer)   AS sprint_speed,
        cast(agility as integer)        AS agility, 
        cast(reactions as integer)      AS reactions,
        cast(balance as integer)        AS balance,
        cast(shot_power as integer)     AS shot_power,
        cast(jumping as integer)        AS jumping,
        cast(stamina as integer)        AS stamina,
        cast(strength as integer)       AS strength,
        cast(long_shots as integer)     AS long_shots, 
        cast(aggression as integer)     AS aggression,
        cast(interceptions as integer)  AS interceptions,
        cast(positioning as integer)    AS positioning,
        cast(vision as integer)         AS vision,
        cast(penalties as integer)      AS penalties,
        cast(marking as integer)        AS marking,
        cast(standing_tackle 
            as integer)                 AS standing_tackle,
        cast(sliding_tackle as integer) AS sliding_tackle, 
        cast(gk_diving as integer)      AS gk_diving, 
        cast(gk_handling as integer)    AS gk_handling,
        cast(gk_kicking as integer)     AS gk_kicking,
        cast(gk_positioning as integer) AS gk_positioning, 
        cast(gk_reflexes as integer)    AS gk_reflexes
    FROM {{ref('Player_Attributes_dbt')}}
